
package com.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceTest", targetNamespace = "http://WebServiceTest.ztesoft.cutter.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceTest {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test1", targetNamespace = "http://WebServiceTest.ztesoft.cutter.cn", className = "com.cxf.client.Test1")
    @ResponseWrapper(localName = "test1Response", targetNamespace = "http://WebServiceTest.ztesoft.cutter.cn", className = "com.cxf.client.Test1Response")
    public String test1();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.cxf.client.ResultBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test3", targetNamespace = "http://WebServiceTest.ztesoft.cutter.cn", className = "com.cxf.client.Test3")
    @ResponseWrapper(localName = "test3Response", targetNamespace = "http://WebServiceTest.ztesoft.cutter.cn", className = "com.cxf.client.Test3Response")
    public ResultBean test3(
        @WebParam(name = "arg0", targetNamespace = "")
        CreateUserReq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.cxf.client.WebServiceObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test2", targetNamespace = "http://WebServiceTest.ztesoft.cutter.cn", className = "com.cxf.client.Test2")
    @ResponseWrapper(localName = "test2Response", targetNamespace = "http://WebServiceTest.ztesoft.cutter.cn", className = "com.cxf.client.Test2Response")
    public WebServiceObj test2(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServiceObj arg0);

}
